version: '3'
services:
  thermos:
    container_name: thermos
    image: ghcr.io/truncj/thermos:latest
    restart: always
    privileged: true
    volumes:
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    network_mode: host
  redis:
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    image: "redis:6.0.12-alpine"
    restart: always
    volumes:
      - ./redis-data:/data
    network_mode: host
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
      - ./grafana-storage:/var/lib/grafana
    network_mode: host
  prometheus:
    container_name: prometheus
    image: prom/prometheus-linux-armv7
    restart: always
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus' 
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    network_mode: host

